export const ErrorCodes = {
  AIRPORT_NOT_FOUND: 'AIRPORT_NOT_FOUND',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  INVALID_RADIUS: 'INVALID_RADIUS',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

